### ISSUE TITLE
Windows 10 notifications

### ISSUE THREAD

**Issue by BruceFraser1** [jonaskohl/CapsLockIndicator#31] opened 2019-04-30 13:04 UTC
Hi Jonas,
Congratulations on top notch software design and implementation. Example: users can choose where on the screen the notification will appear.
One little request: it's not necessary for Windows 10 to pop up with the notification "You can show CapsLock Indicator again by double-clicking on this icon" EVERY SINGLE TIME Windows starts. It gets tiresome after a while, having to close that notification.
Besides, the message doesn't give any clue as to what "this icon" is.

**Comment by jonaskohl** [comment] 2019-05-02 07:30
Duplicate of #29

**Closed by jonaskohl** 2019-05-02 07:30 UTC
