### ISSUE TITLE
unexpected "eolText" message

### ISSUE THREAD

**Issue by sztranyovszky** [jonaskohl/CapsLockIndicator#158] opened 2023-02-21 08:38 UTC
Upon clicking on "Check for updates" the following appears:
![image](https://user-images.githubusercontent.com/11715183/220291889-bec88fa1-f590-4319-8a13-9e0438af7cbb.png)

**Comment by jonaskohl** [comment] 2023-02-21 08:56
Duplicate of #155

**Closed by jonaskohl** 2023-02-21 08:56 UTC
Labels: duplicate
