### ISSUE TITLE
Allow for multiple key overlays

### ISSUE THREAD

**Issue by ragkag** [jonaskohl/CapsLockIndicator#156] opened 2023-02-10 21:39 UTC
I really like this utility.  It does everything well BUT if you configure more than one "lock" key and have defined in "Notifications" that the "lock'" keys are persistent, the on screen display overlaps the other "lock" key.  Example: If I have the Caps and Num lock keys set as persistent, if I press the caps lock key it is displayed in the "overlay" position.  If I then press the Num lock key, it is displayed in the same "overlay" position, hiding the Cap lock onscreen indicator.  If I then press the Num lock key again, the Num Lock onscreen display disappears (as it should) but the Caps lock onscreen indicator disappears also, even though I have defined it as persistent.

**Comment by jonaskohl** [comment] 2023-02-21 09:06
Duplicate of #112

Also, next time please include a short, meaningful synopsis of your issue in your title

**Closed by jonaskohl** 2023-02-21 09:06 UTC
Labels: duplicate
