### ISSUE TITLE
cannot uninstall please help

### ISSUE THREAD

**Issue by lewistomlinson** [jonaskohl/CapsLockIndicator#144] opened 2022-10-24 12:07 UTC
Hi I have tried to uninstall the CapsLock Indictor (along with the Number Lock and Scroll Lock) multiple times with no success and it is driving me absolutely insane! It is nowhere to be seen in the Control Pannel and I even went on to live chat with Microsoft support and they could not figure out how to uninstall it either! Please can someone help as it has gone on for so long and I really need it removed

**Comment by jonaskohl** [comment] 2022-10-24 12:52
Duplicate of #49

**Closed by jonaskohl** 2022-10-24 12:52 UTC
Labels: duplicate
