### ISSUE TITLE
Start on logon / Taskbar disappears

### ISSUE THREAD

**Issue by capecemi** [jonaskohl/CapsLockIndicator#59] opened 2020-09-22 15:38 UTC
We have CLI deployed to many users (aws workspaces). We added the exe to the "Run" registry key so that it starts at user logon. Occasionally, users will experience the portion of the taskbar with the system tray icons disappearing. I believe this is related to CLI since it only happens on user logon, it happens to everyone with CLI running at logon, and I've never seen this issue before with any other client. My first question is, Have you seen this issue before and is there a way we can investigate it/confirm CLI is the issue? My second question, Is there a way to enable "Start on logon" in the CLI settings easily, such as through the registry, so we can apply the setting to everyone, and not have to use the "Run" registry key?
![Taskbar_Issue](https://user-images.githubusercontent.com/71718465/93904639-4a100500-fcb7-11ea-8869-c395704ff60b.png)

**Comment by jonaskohl** [comment] 2020-09-24 09:34
First of all, this is a very odd bug. This never has happened to me and I have not heard from any other user having this issue. Maybe this is an edge case with the particular setup you have. And with so many factors that could be the potential culprit, it is difficult to pin down what exactly the problem is, if it even is CLI at all.

To your second question, there is currently no other way of starting CapsLock Indicator at logon, as CLI itself uses the `Run` registry key internally.

**Comment by jonaskohl** [comment] 2021-02-26 13:24
I assume the issue has been fixed and I can close it. Please let me know if that's not the case and I'll reopen the issue.

**Closed by jonaskohl** 2021-02-26 13:24 UTC
Labels: bug, could-not-reproduce, question
